- name: Deploy Webpage to nginx
  become: yes
  hosts: servers
  tasks:
    - name: update cache on Debian/Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution in ["Ubuntu","Debian"]

    - name: install nginx/apache on Ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_distribution in ["Ubuntu","Debian"]

    - name: update cache on Amazon
      dnf:
        update_cache: yes
      when: ansible_distribution in ["Redhat","Amazon"]

    - name: install nginx/apache on Redhat/amazon
      dnf:
        name: nginx
        state: latest
      when: ansible_distribution in ["Redhat","Amazon"]

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: copy webpage to server destination
      copy:
        src: index.html
        dest: /var/www/html
      when: ansible_distribution in ["Ubuntu","Debian"]
